set -g history-limit 500000
set-environment -g "LC_ALL" "en_US.UTF-8"
set-environment -g "LANG" "en_US.UTF-8"
set-environment -g "LANGUAGE" "en_US.UTF-8"
set-environment -g "LC_MESSAGES" "en_US.UTF-8"
set-environment -g "LC_MONETARY" "fi_FI.UTF-8"
set-environment -g "LC_PAPER" "fi_FI.UTF-8"
set-environment -g "LC_MEASUREMENT" "fi_FI.UTF-8"
set-environment -g "LC_ADDRESS" "fi_FI.UTF-8"
set-environment -g "LC_TIME" "fi_FI.UTF-8"


# status bar
set -g status-right "#(pomo)"
set -g status-style "fg=#c2c4ff"
set -g status-left-style "fg=#928374"

set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left ""

# rename panes to current working directory
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'


# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# term colors, these are the correct ones according to neovim checkhealth
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',xterm-256color:RGB'
