set nocompatible
filetype indent plugin on
syntax on

set autochdir
set encoding=utf-8
set background=dark
colorscheme ron
set shell+=\ -O\ globstar

set number
set relativenumber
set ruler
set laststatus=2
set showcmd
set cmdheight=2
set mouse=a

set hidden
set wildmenu
set wildmode=longest,list,full
set incsearch
set hlsearch
set ignorecase
set smartcase

set autoindent
set backspace=indent,eol,start
set path+=**
set tabstop=8
set shiftwidth=4
set softtabstop=4
set expandtab

set confirm
set visualbell
set t_vb=
