[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "grep", "head" ]
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "find", "grep" ]
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "odoo", "sleep", "curl", "kill" ]
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "find", "xargs" ]
modes = [ "default", "autoEdit", "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "odoo" ]
allowRedirection = true
modes = [ "yolo" ]

[[rule]]
decision = "allow"
priority = 950
toolName = "run_shell_command"
commandPrefix = [ "odoo", "grep" ]
allowRedirection = true
modes = [ "default", "autoEdit", "yolo" ]
