background {
    path = screenshot
    blur_passes = 2
    brightness = 0.5
}

input-field {
    size = 320, 56
    position = 0, 0
    halign = center
    valign = center
    outer_color = rgb(8ce7d0)
    inner_color = rgb(152238)
    font_color = rgb(f3f5f9)
}
