#!/usr/bin/bash

case "$1:$2" in
    device_mounted:ba8e75fc-eab1-4cd9-a896-503ca390f57d) /usr/bin/systemctl start syncthing@elmeri.service ;;
    device_unmounted:ba8e75fc-eab1-4cd9-a896-503ca390f57d) /usr/bin/systemctl stop syncthing@elmeri.service ;;
esac
